services:
  webapp:
    build: ./go
    environment:
      ISUCON_DB_HOST: 127.0.0.1
      ISUCON_DB_PORT: 3306
      ISUCON_DB_USER: isucon
      ISUCON_DB_PASSWORD: isucon
      ISUCON_DB_NAME: isuports
    network_mode: host
    volumes:
      - /home/isucon/webapp/tenant_db:/home/isucon/webapp/tenant_db
      - /home/isucon/webapp/sql:/home/isucon/webapp/sql
      - /home/isucon/webapp/public.pem:/home/isucon/webapp/public.pem:ro
      - /home/isucon/initial_data:/home/isucon/initial_data
      - /home/isucon/tmp:/home/isucon/tmp
    init: true

  datadog:
    build: datadog
    pid: host
    environment:
     - DD_API_KEY=${DD_API_KEY}
     - DD_SITE=datadoghq.com
     - DD_LOGS_ENABLED=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro

