name: go

on:
  push:
    paths:
      - go/**
      - docker-compose-go.yml
      - .github/workflows/go.yml
  workflow_dispatch:

permissions:
  contents: read

# 同じワークフロー/同じブランチで実行中ジョブがあれば自動停止させる
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go/go.mod'

      - run: make
        working-directory: go

      - run: docker compose -f docker-compose-go.yml build
